### ISSUE TITLE
questions for SV cluster detection

### ISSUE THREAD

**Issue by jiadong324** [parklab/ShatterSeek#10]
Hi,

I read through the tutorial, which is nice. But I am not so clear on description "**_SVs are interleaved if the genome regions bridged by their breakpoints overlap but not nested_**". Suppose we have two SVs at [1000, 2000] and [1800, 3500]. The breakpoints overlap exist, thus these two intervals can have edge on the graph. But what do you mean by nested? Is that mean a SV is inside another one? Let's say [1000, 2000] and [1200, 1800].

Thanks!

**Comment by isidroc** [comment]
Hello,
Your example [1000, 2000] and [1800, 3500] would be interleaved.
[1000, 2000] and [1200, 1800] would be nested (that is, one contained inside the other).
Best

**Comment by jiadong324** [comment]
Thanks!

My purpose is complex SVs, such as deletion-inversion. Therefore, I do  breakpoints clustering at the first step. My question is: if I use classic clustering algorithm with self-defined distance measure to find clusters, such as hierarchical clustering. What do you think of this process compare to the graph approach?

Best

**Comment by isidroc** [comment]
Hello, I cannot give you an accurate answer, as we have not tested that.
Best,
Isidro

**Comment by jiadong324** [comment]
@isidroc Hi, I notice the input of ShatterSeek requires SCNA status, especially total_cn. Do you have any recommended tools to get such data?

**Comment by isidroc** [comment]
I would certainly recommend the PCAWG pipeline.
