### ISSUE TITLE
issue about layout with plots_chr[[4]]

### ISSUE THREAD

**Issue by riddlexue** [parklab/ShatterSeek#11]
hi, ShatterSeek team
thank you for this wonderful tool to analyze chromothripsis. I have check your recent publication on nature genetics, it seems that the figure layout in your paper is quite different from the default layout in the R package. Especially the info in plots_chr[[4]],  the figure from the ng paper have much more information to determine whether the event is high or low confidence. By contrast, the default layout only have very limited info. Could you please show me how to generate the same layout as shown in your figure? 
Thanks a lot. 

The panel in the paper is like
![image](https://user-images.githubusercontent.com/43985319/76873881-5307c000-68a9-11ea-851d-a77cb5938425.png)

The default panel in R is like
![image](https://user-images.githubusercontent.com/43985319/76874104-a417b400-68a9-11ea-9f06-0e318e49c41c.png)

**Comment by isidroc** [comment]
Hello,
Thanks for your interest in our package. 
You can add more information to the plot by modifying lines 278-314 in https://github.com/parklab/ShatterSeek/blob/master/R/plot_function.R.
 As all the output information is passed as argument to the plot function you can easily add whatever feature you are interested in.
Best wishes,
