### ISSUE TITLE
Merge copy number segments to have different copy number values in adjacent segments

### ISSUE THREAD

**Issue by tgong1** [parklab/ShatterSeek#12]
Hi Isidro,

Our copy number segment file has adjacent entries with same copy number values. So I have tried your code to merge them. 

However,I found it actually doubled the copy number entries by adding copy number segment of width 1 between original copy number entries. I think it will double the number of oscillation between 2 CN states and eventually affect the results of high-confidence chromothripsis region detection. There are also some entries with copy number of 150001. Are those supposed to see? Did I miss anything?

I have also tried to merge by myself, as following:
## d is a data.frame with colums: chr, start, end, total_cn
d$numeric_chrom <- as.character(d$chrom)
  d[d$numeric_chrom == "X",]$numeric_chrom <- "23"
  d$numeric_chrom <- as.numeric(d$numeric_chrom)
  d$total_cn <- as.numeric(d$total_cn)
  tmp <- group_by(d,Diff = (cumsum(c(1,diff(total_cn)) | c(1,diff(numeric_chrom)) !=0 )))
  dd <- summarise(tmp, numeric_chrom = c(numeric_chrom)[1], start = c(start)[1],end = c(end)[length(c(end))], total_cn = mean(total_cn))
  dd$chrom <- as.character(dd$numeric_chrom)
  dd[dd$chrom == "23",]$chrom <- "X"
  dd <- data.frame(chrom=dd$chrom, start=dd$start, end=dd$end, total_cn=dd$total_cn)
  d <- dd

What I found is that some samples have all chromothripsis regions having same max_number_oscillating_CN_segments_2_states and max_number_oscillating_CN_segments_2_states. Is this expected to see?

Thank you in advance for any comments and suggestions!

Tingting

**Comment by isidroc** [comment]
Hi Tingting,
Thanks for your interest in our package. Could you please upload an example with the copy number data format you are using? 
Thanks

**Comment by tgong1** [comment]
Hi Thank you for your reply! I've uploaded one example of CNV data (d.txt) I've been used. Here dd.txt is the CNV data merged using my code and dd1.txt is the merged CNV data by the code you provided.
Thank you!


[dd.txt](https://github.com/parklab/ShatterSeek/files/4850819/dd.txt)
[dd1.txt](https://github.com/parklab/ShatterSeek/files/4850820/dd1.txt)
[d.txt](https://github.com/parklab/ShatterSeek/files/4850821/d.txt)

**Comment by isidroc** [comment]
I think the issue might be that the same position is found in two lines, see e.g.:

chrom	start	end	total_cn
1	11034	46221	2
1	46221	92792	1

Can you change the input CN data (i.e. d.txt) to something like and try again?

chrom	start	end	total_cn
1	11034	46220	2
1	46221	92791	1

Thanks

**Comment by isidroc** [comment]
Given that I have not received further comments I close this issue. Thanks for reporting
