### ISSUE TITLE
Interpreting the results

### ISSUE THREAD

**Issue by beginner984** [parklab/ShatterSeek#13]
Sorry this is not an issue with your software at all

I have run your software on one of my samples, but from the results I really don't know if this sample has chromotripsis or not.

**_For instance, pval_fragment_joins for 3 chromosomes is < 0.05 but in conclusion I don't know if I could call this sample having chromotripsis  or not_**

Even by visualize inspection  can not say

I saw this 

```
pval_fragment_joins > 0.05
chr_breakpoint_enrichment < 0.05
pval_exp_cluster < 0.05
number_DEL + number_DUP + number_h2hINV + number_t2tINV >=3
number_TRA>=4
max_number_oscillating_CN_segments_2_states>=7
```
If this criteria be true for `only one chromosome`, can we call that `sample` with chromotripsis

I have attached my results here if you please give me an intuition

Thank you so much for any help

[My_output.txt](https://github.com/parklab/ShatterSeek/files/5593951/My_output.txt)
![Rplot](https://user-images.githubusercontent.com/43682980/100173513-9697dc80-2ec2-11eb-8452-89b5c614fd12.png)

**Comment by isidroc** [comment]
Replied via email

**Comment by raulfalcao** [comment]
I have the same issue. Could you share the answer? Btw, @isidroc I sent you an email asking for it with my output attached.

**Comment by raulfalcao** [comment]
I faced the same issue. Could you share the answer? Btw, @isidroc I sent you an email asking for it with my output attached.

**Comment by think-o** [comment]
> Replied via email

Hi @isidroc I am also trying to understand the same. Can I get some idea on how to consider the parameters outlined in the issue above, to filter the high-confidence and low-confidence chromothripsis events
