### ISSUE TITLE
Having circos plot

### ISSUE THREAD

**Issue by MaryGoAround** [parklab/ShatterSeek#14]
Thank you so this software

Can I please have access to a sample code for plotting the chromotripsis by a circos as your paper or what is in the tutorial file?

Thanks a million

**Comment by isidroc** [comment]
Hello, we used biocircos for plotting. You can see examples in the Chromothripsis Explorer:
http://compbio.med.harvard.edu/chromothripsis/
https://www.nature.com/articles/s41467-020-16785-6
