### ISSUE TITLE
Is ShatterSeek compatible with hg19 and hg38 coordinates ?

### ISSUE THREAD

**Issue by masaver** [parklab/ShatterSeek#15]
Dear ShatterSeek team,

I have a couple of questions regarding the method and its output(s):

1.	If I understood the method correctly, the statistical criteria used for detecting Chromothripsis, do not depend on whether the SVs and CNs coordinates come from a hg19  or hg38 reference genome. Is this correct?

2.	In line with the previous question, and regarding to the output of plot_chromothripsis(), you indicate in the documentation that  only hg19 idiograms are supported. Does this mean that the remaining plot are based solely on chromosome coordinates, irrespective of whether they come from hg19 or hg38 ?

3.	As it was mentioned in #14, How do you generate the Circos plots that you use to represent the Chromothripsis events? Could you share an example code for that ?

Thanks in advance for the help!

Best,

-Mathias

**Comment by isidroc** [comment]
Hello Mathias,
Thanks for your comments. 
1. That is correct.
2. You are right
3. We generated circos plots for our paper, but did not include that in ShatterSeek. We usually use biocircos to generate such plots. As this is not directly related to ShatterSeek functionalities please send me an email if you want to discuss further in this regard. 
Best,
Isidro
