### ISSUE TITLE
Definition of copy number oscillation

### ISSUE THREAD

**Issue by yutito** [parklab/ShatterSeek#16]
Thank you for this great work.

I understand the basic idea written in the supplementary note. 
If the copy number status in the SV cluster is 1-2-1-2-1-2, the number of CN segments is 6 in total and the oscillating copy number between 2 CN states is also 6. Is it right?

In the example case(DO17373), in chromosome 2, there are only two CN states (1 and 2). 
However, in shatterseek result (attached this file), "max_number_oscillating_CN_segments_3_states" is the same number as "max_number_oscillating_CN_segments_2_states".
What does this mean? How to define "max_number_oscillating_CN_segments_3_states" ?

Related to this, in your original paper, canonical chromothripsis is defined as the event which has more than 60% of the segments oscillate between two CN states. So Is it OK to calculate "max_number_oscillating_CN_segments_2_states" / "number of CN segments"?(For example, in the upper case, this value is supposed to be 1.)

----------
Lastly, I found there might be some mistakes in plot_function.R.
I could not change the color for SV types when drawing the plot using the plot_chromothripsis. This is because, in the function, the color is assigned directly again such as lines 101 to 104 apart from the arguments.
Could you please fix the code?

Thank you for your generous supports!

Best,
Yuta

[github.txt](https://github.com/parklab/ShatterSeek/files/6241554/github.txt)

**Comment by isidroc** [comment]
Hello Yuta,
Thanks for reporting. I have now fixed the plot_function issue you raised.

As for your questions:
(1) CN oscillations. The 2 and 3 states report the number of copy number segments in the regions encompassing the SV cluster that oscillate between 2 and 3 copy number values, respectively. This was necessary to identify regions with oscillations that also contained sporadic alterations mapping to the region with oscillations, such as amplifications. Just considering oscillations between 2 states would not account for this phenomenon, which we found to happen frequently in cancer genomes.
(2). Canonical. Yes, you can compute the fraction of copy number oscillations between 2 states divided by the number of segments in the region delimited by the SV cluster.
Hope this helps,
Isidro

**Comment by think-o** [comment]
> Thank you for this great work.
> 
> I understand the basic idea written in the supplementary note. If the copy number status in the SV cluster is 1-2-1-2-1-2, the number of CN segments is 6 in total and the oscillating copy number between 2 CN states is also 6. Is it right?
> 
> In the example case(DO17373), in chromosome 2, there are only two CN states (1 and 2). However, in shatterseek result (attached this file), "max_number_oscillating_CN_segments_3_states" is the same number as "max_number_oscillating_CN_segments_2_states". What does this mean? How to define "max_number_oscillating_CN_segments_3_states" ?
> 
> Related to this, in your original paper, canonical chromothripsis is defined as the event which has more than 60% of the segments oscillate between two CN states. So Is it OK to calculate "max_number_oscillating_CN_segments_2_states" / "number of CN segments"?(For example, in the upper case, this value is supposed to be 1.)
> 
> Lastly, I found there might be some mistakes in plot_function.R. I could not change the color for SV types when drawing the plot using the plot_chromothripsis. This is because, in the function, the color is assigned directly again such as lines 101 to 104 apart from the arguments. Could you please fix the code?
> 
> Thank you for your generous supports!
> 
> Best, Yuta
> 
> [github.txt](https://github.com/parklab/ShatterSeek/files/6241554/github.txt)

Hi,

The basic example really helps! But may I know how the copy number oscillations are being calculated? How does 1-2-1-2-1-2 equate 6? 

ShatterSeek reports the segments in two columns "max_number_oscillating_CN_segments_2_states" and "max_number_oscillating_CN_segments_2_states_chr" ? What has to be considered further in the analysis? The same goes for 3 states.


Thanks,
Malini
