### ISSUE TITLE
Link to visualizations is broken

### ISSUE THREAD

**Issue by mchaisso** [parklab/ShatterSeek#18]
Hi, I was going to explore some of this data, and the link was a dead link:
http://compbio.med.harvard.edu/chromothripsis/

Thanks,
-Mark

**Comment by mchaisso** [comment]
Though if it's the same figures as https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-019-0576-7/MediaObjects/41588_2019_576_MOESM6_ESM.pdf, the link is good enough.

**Comment by isidroc** [comment]
The service has been restored now. Thanks

**Comment by mchaisso** [comment]
Weird, I still get 404 not found.
