### ISSUE TITLE
Error in h (simpleError (msg, call)):    Error when evaluating the argument 'x' in the method selection for function 'nrow': 'to' must be a finite number

### ISSUE THREAD

**Issue by masaver** [parklab/ShatterSeek#19]
Hello ShatterSeek team,
 I have recently encountered the following error when attempting to run ShatterSeek:

`Error in h (simpleError (msg, call)):
   Error when evaluating the argument 'x' in the method selection for function 'nrow': 'to' must be a finite number`

From what I can tell, the error happens in the statistical_criteria function, in lines 148-168, where the calculation of idxa and idxb happen.

For your convinience, and if it is of any help, I've created .rds files with the SV_data and CNV_data in question, which you can download here: https://www.dropbox.com/sh/s0stt5vuvzst5m4/AADn03oezu4F8mdwoqa1JkXOa?dl=0

To run ShatterSeek, I simply run: `shatterseek( SV_data , CNV_data )`

Any help figuring out this error will be much appreciated.

Best,

-Mathias

**Comment by isidroc** [comment]
Hi Mathias, 
Can you please send the examples in txt/csv format?
Thanks

**Comment by masaver** [comment]
Here are the files.

Best,

-Mathias

**Comment by isidroc** [comment]
Sorry, did you miss the attachments? Thanks

**Comment by isidroc** [comment]
Closing due to lack of follow up.
