### ISSUE TITLE
hg38 support

### ISSUE THREAD

**Issue by tcashby** [parklab/ShatterSeek#2]
Cool R package!

Any plans on adding hg38 support?

If not, could I just modify chr_info.rds to get it working?

**Comment by isidroc** [comment]
Thanks. Yes, I think that would work. Happy to accept a pull request if you modify the code.

**Comment by lindakohn** [comment]
Seems like a nice package. Have you come any further in adding support for hg38?

**Comment by isidroc** [comment]
Hello, thanks for your positive comment. Not yet, please seem my first response for a quick fix you could do on your end. Best wishes

**Comment by a00101** [comment]
I'm sorry, can you upload a file modified with hg38?

**Comment by isidroc** [comment]
There you go

You can convert it to rds by running
chr_info=read.table("chr_info_hg38_for_shatterseek.txt",header=T)
saveRDS(chr_info, 
[chr_info_hg38_for_shatterseek.txt](https://github.com/parklab/ShatterSeek/files/4455879/chr_info_hg38_for_shatterseek.txt)
file="chr_info_hg38.rds")
