### ISSUE TITLE
can't change color in plot_chromothripsis

### ISSUE THREAD

**Issue by ahwanpandey** [parklab/ShatterSeek#21]
Hello,

Thanks for this tool!

I don't seem to be able to change the colors for the various SV types in the method "plot_chromothripsis". Are these hard coded? They always stay as the defaults:

```
DEL_color='darkorange1'
DUP_color='blue1'
t2tINV_color="forestgreen"
h2hINV_color="black"
```

Thanks,
Ahwan

**Comment by isidroc** [comment]
Yes, this is hard-coded now to keep consistency across projects on our end. However, you could add this option in a branch. Thanks a lot for your interest in our tool
