### ISSUE TITLE
ShatterSeek PCAWG High Confidence and Low Confidence cutoffs

### ISSUE THREAD

**Issue by ahwanpandey** [parklab/ShatterSeek#22]
Hello,

Thanks again for this tool. I just really wanted to make sure I am doing the correct interpretation of the output of the tool and would really appreciate if you could have a look at my workflow. It is quite important that I do this right for a paper we are about to publish.

I've been trying to implement the cutoffs that are mentioned in the supplementary methods of the PCAWG paper:
https://www.nature.com/articles/s41588-019-0576-7

Namely, the section:

> 1.2 Confidence of chromothripsis calls
> After visual inspection of a number of chromothripsis calls, we considered as high-confidence
> chromothripsis those regions satisfying at least one of the following sets of cut-off values for the
> statistical criteria described above: (i) at least 6 interleaved intrachromosomal SVs, 7 adjacent
> segments oscillating between 2 CN states, the fragment joins test, and either the chromosomal
> enrichment or the exponential distribution of breakpoints test; and (ii) at least 3 interleaved
> intrachromosomal SVs and 4 or more interchromosomal SVs, 7 adjacent segments oscillating
> between 2 CN states and the fragment joins test. Given that the oscillating CN pattern is often
> only partly retained in chromothripsis events in Bone-Osteosarc, SoftTissue-Leiomyo, and
> SoftTissue-Liposarc tumors due to subsequent amplification events1,10,11, we also considered as
> high-confidence chromothripsis regions those detected in these cancer types involving at least
> 40 intra- or interchromosomal SVs, and satisfying the fragments joins test (this change in criteria
> affects six samples, but, because many of them have multiple events, only one sample that
> previously was not identified as having chromothripsis was identified as having one event).
> We classified as low-confidence those chromothripsis regions meeting the following cut-off
> values: at least 6 interleaved intrachromosomal SVs, 4, 5 or 6 adjacent segments oscillating
> between 2 CN states (following the criteria previously used2), the fragment joins test, and either
> the chromosomal enrichment or the exponential distribution of breakpoints test. Therefore, the
> main difference between the low- and high-confidence calls resides in the number of oscillating
> CN segments.

I am interpreting the above as passing any of the following 3 High Confidence filters:

```
# HC1 : High confidence recommendation by PCAWG and Shatterseek tutorial.pdf
- at least 6 interleaved intrachromosomal SVs, 
- 7 contiguous segments oscillating between 2 CN states, 
- failing the fragment joins test,  (i.e. pval is not significant)
- passing (either the chromosomal enrichment ) or (the exponential distribution of breakpoints test.) [i.e. pval is significant]

# HC2 : High confidence recommendation by PCAWG and Shatterseek tutorial.pdf
- at least 3 interleaved intrachromosomal SVs
- 4 or more interchromosomal SVs
- 7 contiguous segments oscillating between 2 CN states
- failing the fragment joins test.  (i.e. pval is not significant)

# HC3 : High confidence recommendation by PCAWG
- high-confidence chromothripsis regions those detected in these cancer types involving at least
- 40 intra or interchromosomal SVs
- failing the fragments joins test  (i.e. pval is not significant)

# Low confidence: LC1
- at least 6 interleaved intrachromosomal SVs, 
- 4, 5 or 6 adjacent segments oscillating between 2 CN states, 
- failing the fragment joins test,  (i.e. pval is not significant)
- passing (either the chromosomal enrichment) or (the exponential distribution of breakpoints test.) [i.e. pval is significant]
```

So a candidate Chromothripsis event would be passing (HC1 or HC2 or HC3)?

Now, I am interpreting this in R with the ShatterSeek results and the exact columns it generates as:

```
# create a column with the intrachromosomal SVs count for the cluster
all_data$number_intrachromosomal_SVs = all_data %>% dplyr::select(number_DEL,number_DUP,number_h2hINV,number_t2tINV) %>% apply(1,sum)

# 1st High Confidence filter
filt1 = all_data$number_intrachromosomal_SVs >= 6
filt2 = all_data$max_number_oscillating_CN_segments_2_states >= 7
filt3 = all_data$pval_fragment_joins >= 0.05
filt4 = (all_data$chr_breakpoint_enrichment <= 0.05) | (all_data$pval_exp_chr <= 0.05)
HC1 = (filt1) & (filt2) & (filt3) & (filt4)
HC1[is.na(HC1)] <- FALSE
all_data$HC1 <- HC1

# 2nd High Confidence filter
filt1 = all_data$number_intrachromosomal_SVs >= 3
filt2 = all_data$number_TRA >= 4
filt3 = all_data$max_number_oscillating_CN_segments_2_states >= 7
filt4 = all_data$pval_fragment_joins >= 0.05
HC2 = (filt1) & (filt2) & (filt3) & (filt4)
HC2[is.na(HC2)] <- FALSE
all_data$HC2 <- HC2

# 3rd High Confidence filter
filt1 = all_data$clusterSize_including_TRA >= 40
filt2 = all_data$pval_fragment_joins >= 0.05
HC3gte40 = (filt1) & (filt2)
HC3gte40[is.na(HC3gte40)] <- FALSE
all_data$HC3gte40 <- HC3gte40

# Low Confidence filter
filt1 = all_data$number_intrachromosomal_SVs >= 6
filt2 = (all_data$max_number_oscillating_CN_segments_2_states >= 4) & (all_data$max_number_oscillating_CN_segments_2_states <= 6)
filt3 = all_data$pval_fragment_joins >= 0.05
filt4 = (all_data$chr_breakpoint_enrichment <= 0.05) | (all_data$pval_exp_chr <= 0.05)
LC1 = (filt1) & (filt2) & (filt3) & (filt4)
LC1[is.na(LC1)] <- FALSE
all_data$LC1 <- LC1

# all_data$HCany if TRUE means a Chromothripsis event has occurred
all_data$HCany <- all_data$HC1 | all_data$HC2 | all_data$HC3gte40
```

I have 126 samples in my cohort so I will probably use FDR corrected pvalues for any "pval" column. Upon correction, maybe the cutoffs could be adjusted to :
```
all_data$pval_fragment_joins.fdr >= 0.2
(all_data$chr_breakpoint_enrichment.fdr <= 0.1) | (all_data$pval_exp_chr.fdr <= 0.1)
```

I would really appreciate if you could have a look and let me know if I am on the right track or completely off the mark!

Thanks so much for your time.

Ahwan

**Comment by isidroc** [comment]
Dear Ahwan,
Thanks for your message. I reply below:
- "So a candidate Chromothripsis event would be passing (HC1 or HC2 or HC3)?" ---> Yes
- FDR, yes this is a good idea. 
Overall, please also be aware that these cut-off values were determined through visual inspection of calls generated using the PCAWG SV and CNV consensus call sets. Depending on the callers you use for this task you might need to adjust these values. For example, if the copy number caller you use is more sensitive or if you have oversegmentation, you might want to change e.g. the cutoff for the number of oscillations. This is one of the reasons why we recommend visual inspection of calls, as the values of the tests we used are sensitive to the SV and copy number calling process. Happy to follow up by email if you need further help.
Best,
Isidro
