### ISSUE TITLE
Multiple warnings when using tutorial data

### ISSUE THREAD

**Issue by mdiaz09** [parklab/ShatterSeek#24]
Hello,

I am attempting to run ShatterSeek using the information presented in the tutorial before moving onto my datasets. The code I used is the following 

```
library(devtools)
install_github("parklab/Shatterseek", force=TRUE)
library(gridExtra)
library(ShatterSeek)
data(DO17373)

head(SV_DO17373)

SV_data <- SVs (chrom1 = as.character(SV_DO17373$chrom1),
                pos1 = as.numeric(SV_DO17373$start1),
                chrom2 = as.character(SV_DO17373$chrom2),
                pos2 = as.numeric(SV_DO17373$end2),
                SVtype = as.character(SV_DO17373$svclass),
                strand1 = as.character(SV_DO17373$strand1),
                strand2 = as.character(SV_DO17373$strand2))


CN_data <- CNVsegs (chrom = as.character(SCNA_DO17373$chromosome),
                    start = SCNA_DO17373$start,
                    end = SCNA_DO17373$end,
                    total_cn = SCNA_DO17373$total_cn
                    )

chromothripsis <- shatterseek(SV.sample = SV_data, seg.sample = CN_data)
head(chromothripsis@chromSummary)
plots_chr3 <-  plot_chromothripsis(ShatterSeek_output = chromothripsis,chr = "3")
```

`head(SV_DO17373)` returns the same information as in the tutorial PDF  but `chromothripsis <- shatterseek(SV.sample = SV_data, seg.sample = CN_data)` yields 44 errors. Each error is related to SVsnow$pos1 and SVsnow$pos2, for example
`In min(c(SVsnow$pos1, SVsnow$pos2)) :
  no non-missing arguments to min; returning Inf`
`print(head(chromothripsis@chromSummary))` has many NA values after this, which is not the case in the tutorial data.
Is there a missing package that needs to be installed? I am running R version 4.1.1 (2021-08-10) if that is helpful.
Thank you

**Comment by Sontiroycrazy** [comment]
@mdiaz09 
Did you solve the issue? 
I m facing same problem.

**Comment by mdiaz09** [comment]
@Sontiroycrazy 
I was not. The program is able to run and graph (provided you use  < plot_chromothripsis(ShatterSeek_output = chromothripsis, chr = "chr3", sample_name="X" > rather than < chr = "3" > as stated in the tutorial) but it is unclear to me  if the errors impact the final result.

**Comment by isidroc** [comment]
Hello All, sorry for the delay (busy period). This has now been fixed. Thanks for reporting the bug.

**Comment by isidroc** [comment]
And for piece of mind, the results of the chromothripsis calls you might have generated are not affected by any plotting bug (including the one reported in this issue).

**Comment by Sontiroycrazy** [comment]
@isidroc 
Thanks
How to use it for other species data?
Or it need modifications
