### ISSUE TITLE
Warning when running sample data, error while plotting with chr no. and want to if shatter can be use with othrr organism data

### ISSUE THREAD

**Issue by Sontiroycrazy** [parklab/ShatterSeek#27]
I got warning while running the sample data came with the package.

When i try to plot it, it shows error with invalid chr number.

And i did like to use shatterseek with bovine data,  is it possible?

**Comment by Emma1997WTT** [comment]
Hello! I also encountered the same problem, but I solved it by changing the chr parameter in the plot_chromothripsis function from "3" to "chr3". You can give it a try and wish everything goes well.

**Comment by isidroc** [comment]
Hello Sonti and Emma.
Yes, the plot_chromothripsis function is now solved.
Re the warnings, those depend on your input data. I did not suppress them by default for transparency, but you can ignore them.
Re applying ShatterSeek to bovine data. You certainly can. The only thing to change are the annotation files used in the package internally. The SV clustering functions and the functions related to the statistical criteria would work fine. 
Hope this helps,
Isidro
