### ISSUE TITLE
Error in statistical_criteria(): error in evaluating the argument 'x' in selecting a method for function 'nrow': wrong sign in 'by' argument

### ISSUE THREAD

**Issue by xlucpu** [parklab/ShatterSeek#29]
#-----------------------------------------------------#
**DATA ATTACHMENT TO REPRODUCE THE ERROR**
[SV and CN data.zip](https://github.com/parklab/ShatterSeek/files/8087109/SV.and.CN.data.zip)
#-----------------------------------------------------#

Hi there,

I encountered an error like below when running _ShatterSeek_ using genome version of _hg38_.
`Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'nrow': wrong sign in 'by' argument`

Please decompressed the attachment and use the following code and you can reproduce the error:
```
library(ShatterSeek)
SV_data <- readRDS("SV_data.rds")
CN_data <- readRDS("CN_data.rds")
chromothripsis <- 
  shatterseek(SV.sample = SV_data,
              seg.sample = CN_data,
              genome = "hg38")
```

I reviewed carefully from the source code and found it occured in function of _statistical_criteria()_ when running till the following code:
`nb_oscill = ShatterSeek:::fmax2(CNV_window_now[seq(max(idxa),min(idxb),1),],cutoff=1)`

In my data from the compressed file, the max(idxa) is 170 while the min(idxb) is 169 which caused a wrong sign direction.

Could you please help resolving this issue at your convenience?

Many thanks in advance!
Xiaofan

**Comment by isidroc** [comment]
I think the problem is that you have contiguous segments with the same copy number, which is not allowed as input. Please read the README file and documentation. Best, Isidro
<img width="649" alt="Screenshot 2022-02-19 at 15 50 58" src="https://user-images.githubusercontent.com/5588266/154808222-c06916fc-b4be-4baa-933e-aa375368dcec.png">

**Comment by xlucpu** [comment]
> I think the problem is that you have contiguous segments with the same copy number, which is not allowed as input. Please read the README file and documentation. Best, Isidro <img alt="Screenshot 2022-02-19 at 15 50 58" width="649" src="https://user-images.githubusercontent.com/5588266/154808222-c06916fc-b4be-4baa-933e-aa375368dcec.png">

Thanks, it is really helpful!
