### ISSUE TITLE
A question about strands

### ISSUE THREAD

**Issue by Mawh815** [parklab/ShatterSeek#35]
Hi!
  I have a questions about stands .In ShatterSeek,deletion(3 to 5)is +-  ,  duplication(5 to 3)is -+ ,but a h2hINV(++)is 3'o3' or 5'to5'  ?and how about TRA(++)?

**Comment by isidroc** [comment]
Hello, ShatterSeek follows the SV notation convention established by the PCAWG Consortium. You can find more information here: https://www.nature.com/collections/afdejfafdb
Best,
Isidro
