### ISSUE TITLE
support mm10 genome

### ISSUE THREAD

**Issue by noobugs** [parklab/ShatterSeek#36]
Hi ShatterSeek team, thank you so much for such a great package, may I know is there any way to perform ShatterSeek on mm10 mouse genome? the current version seems only support hg19 and hg38. Thank you so much!

**Comment by isidroc** [comment]
Hello, ShatterSeek does not have annotations for mm10. However, you could use ShatterSeek to detect chromothripsis events and visualize them using your own scripts or by preparing the karyotype information for mm10.
