### ISSUE TITLE
Check-up prior to indexing possibly missing

### ISSUE THREAD

**Issue by vladimirtomic** [parklab/ShatterSeek#4]
Hi ShatterSeek Team,

ShatterSeek runs successfully on a number of samples (various combinations of CNV and SV callers) but with one of the samples this error occurs:

```Error in seq.default(max(idxa), min(idxb), 1): wrong sign in 'by' argument```

What happens is that in function_criteria() value of min(idxb) is 354, and max(idxa) is 355, and step argument is 1. Here's the if statement before the error occurs:

https://github.com/parklab/ShatterSeek/blob/b0ddb6b4eb5d655683c4bc97793285fd77d9a850/R/function_criteria.R#L156

Above in the code there is a similar if statement, checking lengths of idxa and idxb, but also checks whether max(idxa) <= min(idxb). Perhaps this check is missing in the reported line.

Please have a look.

Thanks!

Best, Vladimir

**Comment by zhang919** [comment]
Hi @vladimirtomic ,
I recently meet the problem too, could you please give me any idea about fix it? 
Thans for your help.
Best.
Zhang

**Comment by vladimirtomic** [comment]
Hi @zhang919,

I've tried to find if and how I've fixed it, but couldn't find it. We probably skipped the processing of that sample.

Best,
Vladimir

**Comment by zhang919** [comment]
Hi @vladimirtomic,
Thanks for your kindly reply, I found that it can run well in hg38 coordinate system, but it can't run on hg19 converted by liftOver, which is very interesting. All in all this may harmless. Could you allow me to follow up a question, I notice the section "Recommended cut-off values" tell: 

> High confidence: at least 6 interleaved intrachromosomal SVs, 7 contiguous segments oscil-
> lating between 2 CN states, the fragment joins test, and either the chromosomal enrichment
> or the exponential distribution of breakpoints test.
> High confidence: at least 3 interleaved intrachromosomal SVs and 4 or more interchromosomal
> SVs, 7 contiguous segments oscillating between 2 CN states and the fragment joins test.
> Low confidence: at least 6 interleaved intrachromosomal SVs, 4, 5 or 6 adjacent segments os-
> cillating between 2 CN states, the fragment joins test, and either the chromosomal enrichment
> or the exponential distribution of breakpoints test.

I noticed pval_fragment_joins And inter_pval_fragment_joins in the result, I am not sure that it is appropriate to adopt whats one. Could you please give me some suggestions?
Thanks for your reading and help again.
Best.
Zhang

**Comment by vladimirtomic** [comment]
Hi @zhang919, I'd like to help, but I've used ShatterSeek almost two years ago and don't remember any of the details.
