### ISSUE TITLE
Colored dots without connecting lines

### ISSUE THREAD

**Issue by lichennan123** [parklab/ShatterSeek#41]
Hello!

I really love this tool and a lot of discussions over here that helped me a lot when analyzing my data. I noticed that in the SV plot generated by plot_chromothripsis, there were dots in different colors (including black and orange/green/blue) that did not connect to any line. My question is what do these dots mean? Do they represent inter-chromosomal translocation or just local SVs that impact very small regions? If so, does color mean anything for them? Thank you very much.

Sincerely,
Chennan

**Comment by isidroc** [comment]
Dear Chennan,
Thanks a lot. I'd suggest using the updated visualization package we've recently released to inspect chromothripsis calls:
https://github.com/cortes-ciriano-lab/ReConPlot
https://academic.oup.com/bioinformatics/article/39/12/btad719/7460198
Best wishes,
