### ISSUE TITLE
Candidate chromothripsis regions always cover almost the entire chromosome

### ISSUE THREAD

**Issue by weishwu** [parklab/ShatterSeek#7]
The candidate chromothripsis regions called by ShatterSeek with confidence level of 1 or 2 are always more than 100Mb which covers majority of the chromosome. Is this normal? Is there a way to narrow them down?

Thanks,

**Comment by isidroc** [comment]
Hello, 
The region affected by chomothripsis in each chromosome is defined by the size of cluster of interleaved SVs present in the chromosomes. Detecting the clusters is an automatic process. Does this clarify things?
I am not sure what you mean by narrowing them down.
Best,

**Comment by weishwu** [comment]
Thanks for your quick reply.
We were expecting the chromothripsis to be in a narrower region, instead of covering almost the entire chromosome. An example of a called chromothripsis region with highest confidence level is as follow:

chrom | 3
start | 6525951
end | 157513152
confidenceLevel | 2
number_DEL | 4
number_DUP | 16
number_h2hINV | 0
number_t2tINV | 0
number_TRA | 0
clusterSize_including_TRA | 20
number_SVs_sample | 938
number_CNV_segments | 52
pval_fragment_joins | 1.63E-07
chr_breakpoint_enrichment | NA
pval_exp_chr | NA
pval_exp_cluster | 0
max_number_oscillating_CN_segments_2_states | 7
max_number_oscillating_CN_segments_3_states | 29
number_CN_segments_chr | 50
max_number_oscillating_CN_segments_2_states_chr | 7
max_number_oscillating_CN_segments_3_states_chr | 29
inter_number_DEL | 0
inter_number_h2hINV | 0
inter_number_t2tINV | 0
inter_number_DUP | 0
inter_pval_fragment_joins | NA
inter_other_chroms | NA
inter_other_chroms_coords_all | NA

As you can see the length of this called region is 150Mb while chr3 is 160Mb (in mm10). I was wondering if there was any way to make ShatterSeek output smaller regions without changing the inputs.

Thanks,

**Comment by isidroc** [comment]
Please note that the pval_fragment_joins test is  1.63E-07, meaning that you do not have an even distribution of SV types in your region. Hence, this is likely NOT a chromothripsis event. 
The output of ShatterSeek depends on the input, so I do not think it might make sense to output a smaller region that what is determined by the input. If you refer to the plots, you could certainly change the code to do that.

**Comment by weishwu** [comment]
I thought I was supposed to look for significant p-values. Could you verify if my following criteria are correct to select high confidence candidates?

pval_fragment_joins > 0.05
chr_breakpoint_enrichment < 0.05
pval_exp_cluster < 0.05
number_DEL + number_DUP + number_h2hINV + number_t2tINV >=3
number_TRA>=4
max_number_oscillating_CN_segments_2_states>=7

Thanks,

**Comment by isidroc** [comment]
Yes, note: pval_fragment_joins > 0.05, (1.63E-07 < 0.05)
Also, please note that it would be advisable to use multiple testing correction if you apply ShatterSeek to many samples.
Best,
Isidro

**Comment by weishwu** [comment]
Thanks!
