### ISSUE TITLE
Code for assigning confidence to candidate regions

### ISSUE THREAD

**Issue by nadiadavidson** [parklab/ShatterSeek#8]
Hi,
I just wondering if you could provide the R code used to assign candidates as high, medium and low confidence candidates in the 2,600 whole genomes. e.g. which columns of the object returned by shatterseek, p-value cut-off etc. were use? Sorry, if this has already been provided elsewhere and I've missed it.

**Comment by isidroc** [comment]
All the PCAWG calls are provided in the "Supplementary Information" tab at http://compbio.med.harvard.edu/chromothripsis/
Best,

**Comment by nadiadavidson** [comment]
Thanks for your reply. I was hoping to run ShatterSeek on a different dataset, but I'm unsure what p-value cut-off ect. are best.

**Comment by isidroc** [comment]
The cut-off values are described in the tutorial. Have you seen it? 
Please note that if you apply ShatterSeek to many samples you might want to perform multiple testing correction. 
Best

**Comment by nadiadavidson** [comment]
Hi again for your fast response. I've been looking at section 3 of the tutorial, but unsure exactly what the R cut-off would be. I'll give an example, which may you can help with. 

"High condence: at least 6 interleaved intrachromosomal SVs, 7 contiguous segments oscillating
between 2 CN states, the fragment joins test, and either the chromosomal enrichment
or the exponential distribution of breakpoints test."

For 6 interleaved intrachromosomal SVs I have:
(chromothripsis$clusterSize_including_TRA-chromothripsis$number_TRA)>=6
For 7 contiguous segments oscillating between 2 CN states, I have:
chromothripsis$max_number_oscillating_CN_segments_2_states>=7. Can I confirm that 
"max_number_oscillating_CN_segments_2_states_chr" shouldn't be used?
the fragment joins test:
chromothripsis$pval_fragment_joins < ??
either the chromosomal enrichment or the exponential distribution of breakpoints test?
(chromothripsis$chr_breakpoint_enrichment <?? | chromothripsis$pval_exp_cluster <??)
Can I confirm it's not "pval_exp_chr" that's used here?

I thought I read somewhere that you used a p-value threshold of 0.2, but I can't find that now. Does that sound right? Good to know that the p-values haven't been adjusted for multiple testing.
Thanks for your help.

**Comment by isidroc** [comment]
We did adjust the P values in our paper. The cut-off values we used are in the Supplementary Note of our paper (which you can find in bioRxiv).
"max_number_oscillating_CN_segments_2_states_chr" shouldn't be used, because this refers to the number of oscillations across the entire chromosomes, not specific to the region delimited by the cluster of SVs.
I should note that visual inspection is recommended for all cases.
Best,

**Comment by nadiadavidson** [comment]
Thanks for clarifying this. Will close the thread now.
Cheers,
Nadia.
